{% set name = "candlewick" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Simple-Robotics/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: efc9ef18aa8b1d228ebffa289062a9c3ee52de40b3c83d9e2fc3e8cec080d390

build:
  # For the v0.0.2, windows is not available but will be in future realease
  skip: true  # [win]
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - pkg-config
    - make   # [not win]
    - clang  # [win]
    - ninja  # [win]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
  host:
    - assimp
    - coal
    - libcoal
    - eigen
    - eigenpy
    - entt
    - ffmpeg
    - libboost-python-devel
    - magic_enum
    - nlohmann_json
    - numpy
    - pinocchio
    - python
    - sdl3
  run:
    - assimp
    - coal
    - libboost-python-devel
    - pinocchio
    - python
    - sdl3

test:
  commands:
    - test -f $PREFIX/lib/libcandlewick_core$SHLIB_EXT           # [unix]
    - test -f $PREFIX/lib/libcandlewick_multibody$SHLIB_EXT      # [unix]
    - if not exist %LIBRARY_LIB%\\boost_log-vc140-mt.lib exit 1  # [win]

about:
  home: https://github.com/Simple-Robotics/candlewick
  summary: 'Candlewick: a WIP renderer based on SDL_gpu'
  description: |
    Candlewick comes with a set of graphical, interaction, and utility features such as
    Shadow mapping using directional shadow maps, Screen-space ambient occlusion
    (SSAO), integration with ImGui.
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://github.com/Simple-Robotics/candlewick
  dev_url: https://github.com/Simple-Robotics/candlewick

extra:
  recipe-maintainers:
    - ManifoldFR
    - ymontmarin
