{% set name = "candlewick" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Simple-Robotics/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0e0c1afb67b5eeac5e554ca4f1101364224dd93cf9df57d3fe42b07fe3fc176c

build:
  # For the v0.0.2, windows is not available but will be in future realease
  skip: true  # [win]
  number: 3
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - pkg-config
    - clang  # [win]
    - ninja
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
  host:
    - assimp
    - libcoal
    - eigen
    - eigenpy
    - entt
    - ffmpeg
    - libboost-devel
    - libboost-python-devel
    - magic_enum
    - nlohmann_json
    - numpy
    - pinocchio
    - python
    - sdl3
    - msgpack-cxx
    - cli11 2.4.*
    - cppzmq
    - spdlog
    - fmt  # because spdlog need it, but it's not exported in run requirements
    - qhull
    - qhull-static  # [not win]
  run:
    - python
    - qhull-static  # [not win]
    - msgspec
    - pyzmq
    - zeromq

test:
  commands:
    - test -f $PREFIX/bin/candlewick-visualizer           # [unix]
    - test -f $PREFIX/lib/libcandlewick_core$SHLIB_EXT           # [unix]
    - test -f $PREFIX/lib/libcandlewick_multibody$SHLIB_EXT      # [unix]
    - if not exist %LIBRARY_LIB%\\boost_log-vc140-mt.lib exit 1  # [win]

about:
  home: https://github.com/Simple-Robotics/candlewick
  summary: 'Candlewick: a WIP renderer based on SDL_gpu'
  description: |
    Candlewick comes with a set of graphical, interaction, and utility features such as
    Shadow mapping using directional shadow maps, Screen-space ambient occlusion
    (SSAO), integration with ImGui.
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://github.com/Simple-Robotics/candlewick
  dev_url: https://github.com/Simple-Robotics/candlewick

extra:
  recipe-maintainers:
    - jorisv
    - ManifoldFR
    - ymontmarin
